#part 1 = goal, sent by client
string bag_file_name
bool eef_only # If this is set to True - then the target_topic should have EEF Pose values
string target_topic # What topic in the bag file is the goal in (e.g. eef_pose, joint_states)
---
#part 2 = result, sent by server
#how many keyframes recorded
duration time_elapsed
---
#part 3 = feedback, sent periodically during execution
duration time_elapsed

