#part 1 = goal, sent by client
string bag_file_name
bool trajectory
---
#part 2 = result, sent by server
#how many keyframes recorded
uint32 num_keyframes
---
#part 3 = feedback, sent periodically during execution
uint32 num_keyframes

