#!/usr/bin/env python

import sys

from rqt_gui.main import Main

plugin = "rqt_kinesthetic_teaching.rqt_kinesthetic_teaching.KinestheticTeaching"
main = Main(filename=plugin)
#plugin_argument_provider=Bag.add_arguments
sys.exit(main.main(standalone=plugin))